# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/rerost/playground
    steps:
      - checkout
      - run: make build
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/rerost/playground
    steps:
      - docker build -t rerost/playground .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
